apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git-repo
  namespace: '[PIPELINE-NAMESPACE]' # {"type":"string","x-kustomize":{"setter":{"name":"pipeline-namespace","value":"[PIPELINE-NAMESPACE]"}}}
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: '[APP-SRC]' # {"type":"string","x-kustomize":{"setter":{"name":"app-src","value":"[APP-SRC]"}}}
