apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git-repo
  namespace: "[PIPELINE-NAMESPACE]" # {"type":"string","x-kustomize":{"setter":{"name": "pipeline-namespace", "value": "[PIPELINE-NAMESPACE]"}}}
spec:
  type: git
  params:
  - name: revision
    value: v0.32.0
  - name: url
    value: "[APP-REPO-URL]" # {"type":"string","x-kustomize":{"setter":{"name":"app-src", "value": "[APP-REPO-URL]"}}}
