apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: '[PIPELINE-NAMESPACE]' # {"type":"string","x-kustomize":{"setter":{"name":"pipeline-namespace","value":"[PIPELINE-NAMESPACE]"}}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: '[PIPELINE-NAMESPACE]' # {"type":"string","x-kustomize":{"setter":{"name":"pipeline-namespace","value":"[PIPELINE-NAMESPACE]"}}}
secrets:
- name: kaniko-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
  namespace: '[PIPELINE-NAMESPACE]' # {"type":"string","x-kustomize":{"setter":{"name":"pipeline-namespace","value":"[PIPELINE-NAMESPACE]"}}}
type: Opaque
stringData:
  # WARNING: BELOW SHOULD BE REPLACED WITH YOUR OWN GCP SERVICE_ACCOUNT JSON KEY FILE.
  kaniko-secret.json: |-
    {
      "type": "service_account",
      "project_id": "yuwenma-gke-playground",
      "private_key_id": "FAKE-ID",
      "private_key": "FAKE-KEY",
      "client_email": "NOT-EXIST@yuwenma-gke-playground.iam.gserviceaccount.com",
      "client_id": "108370431538100808553",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pipeline-quickstart-robot%40yuwenma-gke-playground.iam.gserviceaccount.com"
    }
